name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: GenRF Version
      description: What version of genRF are you running?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: circuit-type
    attributes:
      label: Circuit Type
      description: What type of circuit were you working with?
      options:
        - LNA (Low Noise Amplifier)
        - Mixer
        - VCO (Voltage Controlled Oscillator)
        - PA (Power Amplifier)
        - Filter
        - Custom/Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Initialize CircuitDiffuser with...
        2. Set specifications...
        3. Run generation...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g., Ubuntu 20.04, macOS 12.0, Windows 11]
        - Python: [e.g., 3.9.7]
        - PyTorch: [e.g., 1.12.0]
        - SPICE Engine: [e.g., NgSpice 34, XYCE 7.4]
        - CUDA: [e.g., 11.3, N/A]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      render: shell
      placeholder: Paste error messages here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for similar problems
          required: true
        - label: I have tested with the latest version
          required: false
        - label: I can consistently reproduce this issue
          required: false